version: '3.7'

services:
  db:
    image: postgres:12-alpine
    env_file:
      - ./.env.example
    restart: always
    volumes:
      - acompanha_data:/var/lib/postgresql/data

  api:
    build: api/.
    env_file:
      - ./.env.example
    volumes:
      - nginx:/etc/nginx/conf.d
      - acompanha_static:/var/acompanha_legis/api/static
    depends_on:
      - db

  trigger:
    build: acompanha_legis/.
    depends_on:
      - db

  portal:
    image: camara-data-portal

  nginx:
    image: nginx:alpine
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - nginx:/etc/nginx/conf.d
      - acompanha_static:/var/acompanha_legis/api/static
    depends_on:
      - api
      - portal
    ports:
      - 80:80

volumes:
  acompanha_data:
  acompanha_static:
  nginx:
